### ISSUE TITLE
Problem in IdOpenSSLHeaders_provider for OpenSSL 3.0

### ISSUE THREAD

**Issue by SvenAbeln** [MWASoftware/Indy.proposedUpdate#1]
OpenSSL 3.0 can not be loaded because of a small problem in IdOpenSSLHeaders_provider.

3 functions can not be found, they were actually not introduced in 3.0 but 3.2
OSSL_PROVIDER_get0_default_search_path
OSSL_PROVIDER_load_ex
OSSL_PROVIDER_try_load_ex

Changing the following constants, seemed to fix the problem.
OSSL_PROVIDER_get0_default_search_path_introduced = (byte(3) shl 8 or Byte(**2**)) shl 8 or byte(0);
OSSL_PROVIDER_load_ex_introduced = (byte(3) shl 8 or Byte(**2**)) shl 8 or byte(0);
OSSL_PROVIDER_try_load_ex_introduced = (byte(3) shl 8 or Byte(**2**)) shl 8 or byte(0);

**Comment by MWASoftware** [comment]
Apologies, when I added the "providers" header for FIPS support, I forgot to test with OpenSSL 3.0 and 3.1. These functions were only introduced in 3.2. The correct fix is to change the markup in the IdOpenSSLHeaders_provider.h2pas file and regenerate the headers. This has been done and all seems to work fine. Repo updated.
