### ISSUE TITLE
Does not compile with Delphi for target Linux64

### ISSUE THREAD

**Issue by SvenAbeln** [MWASoftware/Indy.proposedUpdate#3]
I am using Delphi 12.0 and tried compiling this branch for Linux64.
There are currently two small problems:

**IdSSLOpenSSL.pas**
Line 2136: is still using a record as context
change:
  Result := IndyX509_STORE_load_locations(ctx^.cert_store, ACAFile, ACAPath);
to:
  Result := IndyX509_STORE_load_locations(SSL_CTX_get_cert_store(ctx), ACAFile, ACAPath);

**IdOpenSSLHeaders_core.pas**
The type dword is unknown, because unit Windows is not included.
You could use System.Types instead, as it is done in IdOpenSSLHeaders_crypto.pas

change Line 39:
  {$IFDEF WINDOWS},Windows{$ENDIF};
to:
  {$IFDEF VCL_XE3_OR_ABOVE}System.Types{$ELSE}Types{$ENDIF};

**Comment by MWASoftware** [comment]
>Result := IndyX509_STORE_load_locations(ctx^.cert_store, ACAFile, ACAPath);

I missed that one :(
I have updated the repository with your suggested fixes. Please download and verify - I don't have Delphi 12 (linux64), and close the issue if all is OK. I have checked FPC and Delphi 10 (Windows) and all seems fine.

**Comment by SvenAbeln** [comment]
Compiles now
