### ISSUE TITLE
64-bit version loads libcrypto.dll from the Windows\System32 directory

### ISSUE THREAD

**Issue by ddwinai** [MWASoftware/Indy.proposedUpdate#4]
Hi,

The 64-bit version loads libcrypto.dll from the Windows\System32 directory in TOpenSSLLoader.Load. This is the LibreSSL library which is shipped with Windows 10+ and actually contains a large subset of OpenSSL. Of course this will raise EIdOSSLCouldNotLoadSSLLibrary.

Regards,
David

**Comment by MWASoftware** [comment]
> Hi,
> 
> The 64-bit version loads libcrypto.dll from the Windows\System32 directory in TOpenSSLLoader.Load. This is the LibreSSL library which is shipped with Windows 10+ and actually contains a large subset of OpenSSL. Of course this will raise EIdOSSLCouldNotLoadSSLLibrary.
> 
> Regards, David

David,
Have you tried the branch "NewLibLoadStrategy"? This is a more permissive approach that loads all the functions it can and directs run time calls to any unloaded functions to an error handler so that a meaningful exception is raised. The master branch keeps to the old strategy which aborts if any function cannot be loaded.

Regards
Tony

**Comment by ddwinai** [comment]
Hi,

Yes, but this way Windows\System32\libcrypto.dll will be loaded always because is there, even if we ship libcrypto-3-x64.dll in the app dir. Maybe the loader should first look for -3/-3-x64 then if not found try without suffix.

Regards,
David

**Comment by MWASoftware** [comment]
David,
The suffix search order is given in the unit IdSSLOpenSSLConsts and the constant 

DefaultLibVersions = ';-3-x64;-1-x64';

I guess what you are saying is that you want the "no prefix" option to be further down the list. You can always set the list yourself by calling GetOpenSSLLoader.SetSSLLibVersions (unit IdSSLOpenSSLLoader).

Regards
Tony

**Comment by ddwinai** [comment]
Hi,

Yes, my personal preference would be that the "no prefix" option to be further down the list. The dll name coincidence can lead to some confusion.

Thank you,
David

**Comment by MWASoftware** [comment]
Change to library load priority now available in both branches (old and new lib loader)
